-- Create product table
CREATE TABLE IF NOT EXISTS public.product (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  product_name text NOT NULL,
  procuct_price text DEFAULT '0'::text,
  product_category text,
  product_description text,
  product_img jsonb DEFAULT '[]'::jsonb NOT NULL,
  product_size jsonb DEFAULT '[]'::jsonb NOT NULL,
  product_color jsonb DEFAULT '[]'::jsonb NOT NULL,
  product_instock boolean DEFAULT true NOT NULL,
  product_bestsellere boolean DEFAULT false NOT NULL,
  product_new boolean DEFAULT false NOT NULL
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.product(id) ON DELETE CASCADE,
  stock_quantity integer DEFAULT 0 NOT NULL,
  low_stock_threshold integer DEFAULT 5 NOT NULL,
  sku text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create a trigger to automatically update updated_at on inventory
CREATE OR REPLACE FUNCTION public.handle_update_timestamp()
RETURNS trigger AS $$
BEGIN
  new.updated_at = now();
  return new;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER update_inventory_timestamp
  BEFORE UPDATE ON public.inventory
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_update_timestamp();

-- Create a trigger to automatically create an inventory entry when a new product is added
CREATE OR REPLACE FUNCTION public.handle_new_product_inventory()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.inventory (product_id, stock_quantity, low_stock_threshold, sku)
  VALUES (new.id, 10, 5, 'SKU-' || new.id)
  ON CONFLICT DO NOTHING;
  return new;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_product_created
  AFTER INSERT ON public.product
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_product_inventory();

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  order_number text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text NOT NULL,
  guest_email text NOT NULL,
  customer_email text,
  guest_name text,
  guest_phone text,
  shipping_full_name text,
  shipping_phone text,
  shipping_line1 text,
  shipping_line2 text,
  shipping_city text,
  shipping_region text,
  shipping_country text,
  shipping_postal_code text,
  subtotal_pkr integer NOT NULL,
  shipping_fee_pkr integer DEFAULT 0 NOT NULL,
  total_pkr integer NOT NULL,
  discount_amount_pkr integer DEFAULT 0 NOT NULL,
  discount_code text,
  billing_address jsonb,
  payment_method text DEFAULT 'cod'::text NOT NULL,
  notes text,
  user_id uuid
);

-- Create order_items table
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.product(id) ON SET NULL,
  title text NOT NULL,
  unit_price_pkr integer NOT NULL,
  quantity integer DEFAULT 1 NOT NULL,
  line_total_pkr integer NOT NULL,
  size text,
  color text,
  image_url text
);

-- Enable RLS on tables
ALTER TABLE public.product ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Create basic access policies
CREATE POLICY "Allow public read-only access to products" ON public.product FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access to inventory" ON public.inventory FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert to orders" ON public.orders FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public insert to order_items" ON public.order_items FOR INSERT TO public WITH CHECK (true);
