-- 1. If table public.products does not exist, create it
CREATE TABLE IF NOT EXISTS public.products (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  name          TEXT NOT NULL,
  description   TEXT,
  price         NUMERIC DEFAULT 0 NOT NULL,
  category      TEXT,
  color         TEXT, -- Stores JSON string
  size          TEXT, -- Stores JSON string
  img           TEXT, -- Stores JSON string
  instock       BOOLEAN DEFAULT true NOT NULL,
  new           BOOLEAN DEFAULT false NOT NULL,
  bestsellere   BOOLEAN DEFAULT false NOT NULL
);

-- Enable RLS on products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Allow public read on products
DROP POLICY IF EXISTS "Public can read products" ON public.products;
CREATE POLICY "Public can read products"
  ON public.products FOR SELECT
  USING (true);

-- 2. Drop dependent tables to allow changing keys, then re-create them
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;

-- Re-create inventory table referencing public.products(id)
CREATE TABLE public.inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  stock_quantity integer DEFAULT 0 NOT NULL,
  low_stock_threshold integer DEFAULT 5 NOT NULL,
  sku text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Re-enable RLS on inventory
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

-- Create policy for inventory read
DROP POLICY IF EXISTS "Public read inventory" ON public.inventory;
CREATE POLICY "Public read inventory" ON public.inventory
  FOR SELECT USING (true);

-- Re-create trigger for inventory updated_at
CREATE OR REPLACE TRIGGER update_inventory_timestamp
  BEFORE UPDATE ON public.inventory
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_update_timestamp();

-- Create a trigger to automatically create an inventory entry when a new product is added to products
CREATE OR REPLACE FUNCTION public.handle_new_products_inventory()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.inventory (product_id, stock_quantity, low_stock_threshold, sku)
  VALUES (new.id, 10, 5, 'SKU-' || new.id::text)
  ON CONFLICT DO NOTHING;
  return new;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_products_created ON public.products;
CREATE TRIGGER on_products_created
  AFTER INSERT ON public.products
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_products_inventory();

-- Re-create order_items table referencing public.products(id)
CREATE TABLE public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id uuid REFERENCES public.products(id) ON SET NULL,
  title text NOT NULL,
  unit_price_pkr integer NOT NULL,
  quantity integer DEFAULT 1 NOT NULL,
  line_total_pkr integer NOT NULL,
  size text,
  color text,
  image_url text
);

-- Enable RLS on order_items
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- 3. Deploy/Re-deploy RPC fallback functions referencing products and UUID
DROP FUNCTION IF EXISTS public.admin_insert_product_rpc(text, text, text, text, text, jsonb, jsonb, jsonb, boolean, boolean, boolean);
CREATE OR REPLACE FUNCTION public.admin_insert_product_rpc(
  access_key text,
  p_name text,
  p_price text,
  p_category text,
  p_description text,
  p_color jsonb,
  p_size jsonb,
  p_img jsonb,
  p_instock boolean,
  p_bestsellere boolean,
  p_new boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_new_id uuid;
  v_result jsonb;
BEGIN
  IF NOT admin_verify_orders_key(access_key) THEN
    RAISE EXCEPTION 'Unauthorized' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.products (
    name,
    price,
    category,
    description,
    color,
    size,
    img,
    instock,
    bestsellere,
    new
  ) VALUES (
    p_name,
    p_price::numeric,
    p_category,
    p_description,
    p_color::text,
    p_size::text,
    p_img::text,
    p_instock,
    p_bestsellere,
    p_new
  )
  RETURNING id INTO v_new_id;

  SELECT row_to_json(p)::jsonb INTO v_result
  FROM public.products p
  WHERE p.id = v_new_id;

  RETURN v_result;
END;
$$;

DROP FUNCTION IF EXISTS public.admin_update_product_rpc(text, bigint, jsonb);
DROP FUNCTION IF EXISTS public.admin_update_product_rpc(text, uuid, jsonb);
CREATE OR REPLACE FUNCTION public.admin_update_product_rpc(
  access_key text,
  p_id uuid,
  p_updates jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  IF NOT admin_verify_orders_key(access_key) THEN
    RAISE EXCEPTION 'Unauthorized' USING ERRCODE = '42501';
  END IF;

  UPDATE public.products
  SET
    name = COALESCE((p_updates->>'product_name'), name),
    price = COALESCE((p_updates->>'procuct_price')::numeric, price),
    category = COALESCE((p_updates->>'product_category'), category),
    description = COALESCE((p_updates->>'product_description'), description),
    color = CASE WHEN p_updates ? 'product_color' THEN (p_updates->'product_color')::text ELSE color END,
    size = CASE WHEN p_updates ? 'product_size' THEN (p_updates->'product_size')::text ELSE size END,
    img = CASE WHEN p_updates ? 'product_img' THEN (p_updates->'product_img')::text ELSE img END,
    instock = COALESCE((p_updates->>'product_instock')::boolean, instock),
    bestsellere = COALESCE((p_updates->>'product_bestsellere')::boolean, bestsellere),
    new = COALESCE((p_updates->>'product_new')::boolean, new)
  WHERE id = p_id;

  SELECT row_to_json(p)::jsonb INTO v_result
  FROM public.products p
  WHERE p.id = p_id;

  RETURN v_result;
END;
$$;

DROP FUNCTION IF EXISTS public.admin_delete_product_rpc(text, bigint);
DROP FUNCTION IF EXISTS public.admin_delete_product_rpc(text, uuid);
CREATE OR REPLACE FUNCTION public.admin_delete_product_rpc(
  access_key text,
  p_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT admin_verify_orders_key(access_key) THEN
    RAISE EXCEPTION 'Unauthorized' USING ERRCODE = '42501';
  END IF;

  DELETE FROM public.products
  WHERE id = p_id;

  RETURN true;
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_insert_product_rpc(text, text, text, text, text, jsonb, jsonb, jsonb, boolean, boolean, boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_product_rpc(text, uuid, jsonb) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_product_rpc(text, uuid) TO anon, authenticated;

-- Force postgrest cache reload
NOTIFY pgrst, 'reload schema';

-- Seed mock products if not present
INSERT INTO public.products (id, name, description, price, category, color, size, img, instock, new, bestsellere)
VALUES
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f1', 'Olive Embroidered Lawn Suit', 'Embroidered lawn shalwar kameez with flowing dupatta. Demo product for local preview.', 98, 'pants', '[{"name": "Olive", "hex": "#5A6D57", "currentColor": "#5A6D57"}, {"name": "Black", "hex": "#1a1a1a", "currentColor": ""}, {"name": "Sand", "hex": "#C4B8A5", "currentColor": ""}]', '["XS", "S", "M", "L"]', '["/images/pakistani-fashion/stock-1.jpg", "/images/pakistani-fashion/stock-2.jpg"]', true, true, true),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f2', 'Navy Lawn Shalwar Kameez', 'Classic shalwar kameez in soft cotton lawn with tonal embroidery.', 86, 'pants', '[{"name": "Navy", "hex": "#1e2a4a", "currentColor": "#1e2a4a"}, {"name": "Grey", "hex": "#6b7280", "currentColor": ""}]', '["S", "M", "L", "XL"]', '["/images/pakistani-fashion/stock-3.jpg", "/images/pakistani-fashion/stock-4.jpg"]', true, false, false),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f3', 'Charcoal Formal Shalwar Suit', 'Formal black and grey embroidered suit with matching dupatta.', 112, 'pants', '[{"name": "Black", "hex": "#111111", "currentColor": "#111111"}]', '["XS", "S", "M", "L", "XL"]', '["/images/pakistani-fashion/stock-5.jpg", "/images/pakistani-fashion/stock-6.jpg"]', true, false, true),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f4', 'Sage Lawn Eid Suit', 'Light green lawn suit with white dupatta — perfect for Eid gatherings.', 128, 'Dress', '[{"name": "Sage", "hex": "#9CAF88", "currentColor": "#9CAF88"}, {"name": "Ivory", "hex": "#F5F0E8", "currentColor": ""}]', '["S", "M", "L"]', '["/images/pakistani-fashion/stock-7.jpg", "/images/pakistani-fashion/stock-8.jpg"]', true, true, true),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f5', 'Taupe Festive Shalwar Kameez', 'Taupe embroidered dress with pink dupatta for festive evenings.', 142, 'Dress', '[{"name": "Black", "hex": "#0C0C0C", "currentColor": "#0C0C0C"}, {"name": "Burgundy", "hex": "#722F37", "currentColor": ""}]', '["XS", "S", "M", "L"]', '["/images/pakistani-fashion/stock-9.jpg", "/images/pakistani-fashion/stock-10.jpg"]', true, false, false),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f6', 'Purple Embroidered Occasion Suit', 'Purple embroidered outfit with beige shawl — statement occasion wear.', 168, 'outwear', '[{"name": "Olive", "hex": "#5A6D57", "currentColor": "#5A6D57"}, {"name": "Stone", "hex": "#d6d3cd", "currentColor": ""}]', '["S", "M", "L", "XL"]', '["/images/pakistani-fashion/stock-11.jpg", "/images/pakistani-fashion/stock-12.jpg"]', true, true, true),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f7', 'Beige Bridal Lawn Suit', 'Beige embroidered dress with pink accents and refined tailoring.', 195, 'outwear', '[{"name": "Camel", "hex": "#C19a6b", "currentColor": "#C19a6b"}]', '["S", "M", "L"]', '["/images/pakistani-fashion/stock-13.jpg", "/images/pakistani-fashion/stock-14.jpg"]', true, false, false),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f8', 'Blue Lawn Kameez Set', 'Blue embroidered kameez with tan dupatta in breathable lawn.', 64, 'Top & blouses', '[{"name": "White", "hex": "#FFFFFF", "currentColor": "#FFFFFF"}, {"name": "Blue", "hex": "#93b4d4", "currentColor": ""}]', '["XS", "S", "M", "L"]', '["/images/pakistani-fashion/stock-15.jpg", "/images/pakistani-fashion/stock-16.jpg"]', true, true, true),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f9', 'Pink Embroidered Festive Suit', 'Vibrant pink embroidered shalwar kameez for celebrations.', 58, 'Top & blouses', '[{"name": "Blush", "hex": "#e8c4c4", "currentColor": "#e8c4c4"}, {"name": "Black", "hex": "#222222", "currentColor": ""}]', '["S", "M", "L"]', '["/images/pakistani-fashion/stock-17.jpg", "/images/pakistani-fashion/stock-18.jpg"]', true, false, false),
  ('de8f828a-6b88-4db2-a9e9-ea2d8a6e87f0', 'Grey Classic Shalwar Suit', 'Grey traditional outfit with black scarf — understated elegance.', 72, 'Top & blouses', '[{"name": "Stripe", "hex": "#e8e4dc", "currentColor": "#e8e4dc"}, {"name": "Navy", "hex": "#1a2744", "currentColor": ""}]', '["XS", "S", "M", "L", "XL"]', '["/images/pakistani-fashion/stock-1.jpg", "/images/pakistani-fashion/stock-3.jpg"]', true, false, true)
ON CONFLICT (id) DO NOTHING;

